### ISSUE TITLE
cannot search on firefox

### ISSUE THREAD

**Issue by sluongng** [gdh1995/vimium-c#48]
## Issue
Search using `/` shortcut does not accept some characters

## Vimium C version
Version 1.75.6. 

## Reproduce

- Open up some website on firefox.
- Press `/`
- Type "google" to search for instances of google within a page

## Expected result

- Should behave similar to search

## Actual result

- Some characters such as `g`, `f`, `h`, `j` are not accepted as valid input
- Some characters such as `a` or `s` can be input

**Comment by gdh1995** [comment]
Thanks. Confirmed.

And this has been fixed in the master branch (commit 5d8da1c and commit 6a07372), so I'll release a new version in this weekend.

**Comment by gdh1995** [comment]
A new version (1.75.7) of Vimium C has been released on Firefox Addons. Please take a try.

**Comment by sluongng** [comment]
working now

**Comment by sluongng** [comment]
this bug is back as of latest version 1.76.0 on Firefox (stable)

**Comment by gdh1995** [comment]
Confirmed. The build scripts seem wrong.

**Comment by gdh1995** [comment]
Vimium C v1.76.1 has been released to fix this. Sorry for the inconvenience.

**Comment by sluongng** [comment]
1.76.1 fixed it
